### ISSUE TITLE
No module named cv2

### ISSUE THREAD

**Issue by csoto666** [mapircamera/QGIS#1]
Hi, haven't been able to use the plugin and don't know if is related to my os or is a known issue 
thanks
carlo

![screen shot 2016-12-17 at 9 26 10 am](https://cloud.githubusercontent.com/assets/9941392/21336360/5f47dadc-c62a-11e6-951d-5aa9c8e71580.png)

**Comment by csoto666** [comment]
fixed by reinstalling QGIS and dependencies using homebrew

**Comment by mapircamera** [comment]
Hello, I've been trying to get mac support working for so long. I can't seem to add lines to the script to properly set up dependencies. Do you mind letting me know what steps you took so I can support other customers in the future?

**Comment by csoto666** [comment]
hi, here the general steps hope it helps, 
-started by uninstalling qgis (previously downloaded from [)](http://www.kyngchaos.com/software/qgis)
-then installed homebrew a Mac package manager (https://brew.sh/index_es.html)
-using Mac terminal installed requirements, dependencies and finally qgis2, with homebrew 'formulas' (e.g. `brew install qgis2`). more info here [http://usabilityetc.com/2016/06/how-to-install-qgis-with-homebrew](url)
-copy plugin to folder ~/.qgis2/python/plugins/MAPIR_Processing/
-verify dependencies using `brew info qgis2` as shown in image
![screen shot 2017-02-21 at 10 27 40 am](https://cloud.githubusercontent.com/assets/9941392/23173966/7e2de0f4-f820-11e6-8080-773277185762.png)
