### ISSUE TITLE
RAW+JPEG Converted tiff gives poor NDVI results when compared to only JPEG IMAGE.The calibration part was skipped as it was just a Testing.Is the problem due to not calibrating the Image?

### ISSUE THREAD

**Issue by deepzzrs** [mapircamera/QGIS#15]
Camera used : Survey 2 Red + NIR 
Only JPEG : 
![image](https://user-images.githubusercontent.com/33482526/32543375-7258efe2-c49b-11e7-809b-f6ca9756777c.png)

Raw+JPEG, pre processed image : 
![image](https://user-images.githubusercontent.com/33482526/32543410-913c520a-c49b-11e7-8b29-9152cb3cd676.png)

**Comment by mapircamera** [comment]
Hello,

Please download our MAPIR_Camera_Control application, we no longer update or support this project.

**Comment by deepzzrs** [comment]
The results given above was done with the MAPIR_Camera_Control application only and not the QGIS plugin.I just want to know where there might be a mistake, Pre-processing or Calibration Process ?

**Comment by mapircamera** [comment]
Yes, Calibration should help generate better NDVI results, I am looking into a more accurate calibration at this time. THe results will be different, as the Jpeg compression will throw off the NDVI values.

**Comment by deepzzrs** [comment]
So JPEG is better than the RAW for NDVI calculation,Right?

**Comment by mapircamera** [comment]
No, the tiff from the RAW is better than the JPG.

*Peau Productions, Inc*
Toll Free:* +1 (877) 949-1684 <%2B1%20%28877%29%20949-1684>*
Local*: +1 (619) 554-8848 <%2B1%20%28619%29%20554-8848%20x103>*
7592 Metropolitan Dr
Suite 401
San Diego CA 92108 USA
www.peauproductions.com
www.mapir.camera

Skype: peauproductions
Youtube: PeauProductions <http://www.youtube.com/user/PeauProductions>
Facebook: PeauProductions
<https://www.facebook.com/pages/Peau-Productions/287830910468>
