### ISSUE TITLE
MAPIR plugin throwing an error massage

### ISSUE THREAD

**Issue by chekriiam** [mapircamera/QGIS#4]
here is the error message popup...
Couldn't load plugin MAPIR_Processing due to an error when calling its classFactory() method

**Comment by mapircamera** [comment]
Hello, This is often cause because, when extracting the zipped folder, there is a subfolder created also named MAPIR_Processing, navigate to the MAPIR_Processing\MAPIR_Processing folder and copy the contents (All of the .py, .pyc and any other files and folders) into the *\.qgis2\python\plugins\MAPIR_Processing folder.

**Comment by chekriiam** [comment]
hello... thanks for your response, i did the same but still it is showing the same error message. Do i need to clean the registry???

**Comment by mapircamera** [comment]
Possibly, usually it works after I restart QGIS. And if that doesn't work I restart the machine. Let me know if that helps.

**Comment by alcarazolabs** [comment]
Hello dears! I have the same problem. I decided practic with the images from the Avocado Grove proyect
but when I installed it, I had the same problem! I reboot my pc and install python, I made a test with the 2.18-1 version and 2.18.3

No se pudo cargar el complemento MAPIR_Processing debido a un error al llamar a su método classFactory() 

ImportError: No module named hid 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/freydalc94/.qgis2/python/plugins\MAPIR_Processing\__init__.py", line 34, in classFactory
    from .MAPIR_Processing import MAPIR_Processing
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/freydalc94/.qgis2/python/plugins\MAPIR_Processing\MAPIR_Processing.py", line 29, in 
    from MAPIR_Processing_dockwidget import MAPIR_ProcessingDockWidget
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/freydalc94/.qgis2/python/plugins\MAPIR_Processing\MAPIR_Processing_dockwidget.py", line 39, in 
    import hid
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named hid


Versión de Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
Versión de QGIS: 2.18.0 Las Palmas, 0332f5a 

Ruta de Python:
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python
C:/Users/freydalc94/.qgis2/python
C:/Users/freydalc94/.qgis2/python/plugins
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\bin\python27.zip
C:\PROGRA~1\QGIS2~1.18\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS2~1.18\bin
C:\PROGRA~1\QGIS2~1.18\apps\Python27
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/freydalc94/.qgis2//python

**Comment by mapircamera** [comment]
Please make sure you are downloading the latest package from the link on the Packages page. HID dependency was removed from the latest version.

**Comment by alcarazolabs** [comment]
Thanks finally I was able to install the plugin, thanks a lot.
