### ISSUE TITLE
Error - AttributeError: 'module' object has no attribute 'cv2tColor'

### ISSUE THREAD

**Issue by dmalloy** [mapircamera/QGIS#5]
This is a fresh install and first time attempting to process 57 RGB images taken with our Survey2 camera. Have tried latest two versions of the "MAPIR_Processing" plugin with QGIS 2.18.5-2 and QGIS 2.14.13-2 LTR. 
1) Receiving "AttributeError: 'module' object has no attribute 'cv2tColor'" error. 
2) Received the following error in the "Processing" log:
  Problem with OTB installation: OTB was not found or is not correctly installed.
3) Received the following error in the "Plugins" log:
 Failed to load C:/PROGRA~1/QGIS2~1.14/apps/qgis-ltr/plugins/globeplugin.dll (Reason: Cannot load library C:/PROGRA~1/QGIS2~1.14/apps/qgis-ltr/plugins/globeplugin.dll: The specified procedure could not be found.)
I verified that the glodeplugin.dll file is there.

**Comment by mapircamera** [comment]
I thought I had fixed that in the latest package release. Are you downloading from the link in package or using "Download as Zip" option. I have had a bit of trouble with Git commits lately and the hosted code is not as up to date as the release packages.

**Comment by dmalloy** [comment]
I pulled the .zip from https://github.com/mapircamera/QGIS/tree/master/Packages.

**Comment by mapircamera** [comment]
Alright, I'll take a look in a moment.

**Comment by mapircamera** [comment]
This should be fixed in the latest package.

**Comment by dmalloy** [comment]
I have the latest package installed. I just tested the process again and have gotten the errors below in the various tabs:

General Tab
**2017-04-13T10:11:11 1 Failed to load C:/PROGRA~1/QGIS2~1.14/apps/qgis-ltr/plugins/globeplugin.dll (Reason: Cannot load library C:/PROGRA~1/QGIS2~1.14/apps/qgis-ltr/plugins/globeplugin.dll: The specified procedure could not be found.)**
2017-04-13T10:11:15 0 Loaded MAPIR_Processing (package: MAPIR_Processing)
2017-04-13T10:11:15 0 Loaded DB Manager (package: db_manager)
2017-04-13T10:11:15 0 Loaded fTools (package: fTools)
2017-04-13T10:11:16 0 Loaded GdalTools (package: GdalTools)
2017-04-13T10:11:17 0 Loaded MetaSearch Catalogue Client (package: MetaSearch)
2017-04-13T10:11:27 0 Loaded Processing (package: processing)
**(I have checked my files and globeplugin.dll IS is the location specified in the error message)**

Processing Tab
**2017-04-13T10:11:25 2 Problem with OTB installation: OTB was not found or is not correctly installed**
**(I have installed the two latest versions of QGIS as an administrator and this error still shows up)**

Python Error Tab
2017-04-13T10:13:01 1 Traceback (most recent call last):
File C:/Users/u08300/.qgis2/python/plugins\MAPIR_Processing\MAPIR_Processing_dockwidget.py", line 367, in on_PreProcessButton_released
self.preProcessHelper(infolder, outfolder)
File "C:/Users/u08300/.qgis2/python/plugins\MAPIR_Processing\MAPIR_Processing_dockwidget.py", line 1103, in preProcessHelper
color = cv2.cv2tColor(img, cv2.COLOR_BAYER_RG2RGB)
**AttributeError: 'module' object has no attribute 'cv2tColor'**

**Comment by mapircamera** [comment]
Hello, As I've stated in previous issues, the windows extraction tool will sometimes put the package in a subfolder. Make sure that the MAPIR_Processing folder doesn't contain a subfolder named MAPIR_Processing. If it does, then copy the subfolder to the <usernam>/.qgis2/python/plugins folder.

**Comment by dmalloy** [comment]
Hello. The MAPIR_Processing folder was properly moved to the correct location after extraction as indicated in my previous post (see Python Error Tab entries). The following screen print also shows where it is located.

![mapir_processing](https://cloud.githubusercontent.com/assets/26972426/25021901/b0e5cb60-2048-11e7-80f7-a354b424695f.jpg)

**Comment by mapircamera** [comment]
Alright, same error? I'll look into fixing the package. In the mean time, if you open the MAPIR_Processing_dockwidget.py file in a text editor and do a find and replace finding "cv2tColor" and replacing it with "cvtColor". It will solve the above error. That way you don't have to wait for me to roll out the update.

**Comment by dmalloy** [comment]
That worked. I was able to process my images successfully. I now have geotagged tiffs! Thank you.
