### ISSUE TITLE
THIS PLUG IN IS BROKEN

### ISSUE THREAD

**Issue by joupi12** [mapircamera/QGIS#6]
HI! when i try to open the pluggin it says that is broken. I have downloaded the latest one. What should i do? Thanks!

**Comment by mapircamera** [comment]
Hi could you provide an error? Often it is because the folder extracted from our website will create a sub folder containing the actual plugin. Did you download the package from "Packages" or try to download the repository directly?

**Comment by joupi12** [comment]
hi! I dowloaded it from Packages. It says its broken over a over again. I
have the latest Qgis version. Dont know whats happening


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-04-13 11:32 GMT-03:00 MAPIR Camera <notifications@github.com>:

**Comment by mapircamera** [comment]
Hello, I've answered this on the main thread, the plugin doesn't work with the latest version of QGIS.
