### ISSUE TITLE
Plugin wont process nor calibrate(TypeError: 'NoneType')

### ISSUE THREAD

**Issue by Malebolgea** [mapircamera/QGIS#8]
Am i missing something?

![2017-04-17_14-55-37](https://cloud.githubusercontent.com/assets/26681308/25087156/fc5f3f9e-237d-11e7-89cb-945cb8e527d9.png)
`Traceback (most recent call last):

 File "C:/Users/{{USER}}/.qgis2/python/plugins\MAPIR_Processing\MAPIR_Processing_dockwidget.py", line 459, in on_CalibrateButton_released

img[:, :, 2] = img[:, :, 2] - ((img[:, :, 0] / 5) * 4)

TypeError: 'NoneType' object has no attribute '__getitem__'  `

**Comment by mapircamera** [comment]
Hi there,

What type of images are in G:\calper? Does it contain DNGs, JPGs, or TIFFs? If it contains DNGs, you'll need to run those images through the "Process" step before calibrating.

**Comment by Malebolgea** [comment]
Hello.
I've figured it out actually. It was orthomosaic in **compressed** (jpeg 75%) tiff (Default export settings, my mistake) . As soon as i tried using uncompressed tiff - everything works (well, sorta, but thats on my end anyway. Not enough memory to calibrate 4GB full-resolution tiff).
Thanks a lot for coming by though.
